services:
  - type: web
    name: news-aggregator
    env: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn DataFlair_NewsAggregator.wsgi:application"
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.0
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
      - key: ALLOWED_HOSTS
        value: "news-aggregator.onrender.com"
      - key: DATABASE_URL
        fromDatabase:
          name: news-db
          property: connectionString

databases:
  - name: news-db
    databaseName: news_aggregator
    user: news_user
